### ISSUE TITLE
Design and implement squad level equipment

### ISSUE THREAD

**Issue by GalacticChimp** [ZAB909/ChapterMaster#135]
@OH296 has already done a lot of work

current status:

- [x] all units are on game start sorted into squads based on their current unit types;
- [x] squad configurations are determined by json files so that they can be edited readily and redesigned for each chapter as needed
- [x] squads consist of a number of requirements (a minimum for each allowable unit type) and equipment required by the squad
- [x] add options (a maximum number for each allowable unit type) and a range of optional equipment for each given unit type
- [x] optional equipment is distributed via the members of the squad by an algorithm that ensures random allocations, but also ensures individuals do not come overburdened.
- [x] in theory squads are applicable to non marine units if the json files are created, e.g skitarii or ork hirelings
- [x] new unit type sergeants (role[100, 18])
- [x] new unit type veteran sergeants ( role[100, 19]) (both of which are automatically allocated in the squad whenever the existing one dies and selected from the marine with the highest exp)

**Comment by OH296** [comment]
as currently stands the status is thus
- all units are on game start sorted into squads based on their current unit types;
- squad configurations are determined by json files so that they can be edited readily and redesigned for each chapter as needed
- squads consist of a number of requirements  (a minimum for each allowable unit type) and equipment required by the squad
- and options (a maximum number for each allowable unit type) and a range of optional equipment for each given unit type
- optional equipment is distributed via the members of the squad by an algorithm that ensures random allocations, but also ensures individuals do not come overburdened.
- in theory squads are applicable to non marine units if the json files are created, e.g skitarii or ork hirelings

**Comment by GalacticChimp** [comment]
ok, so what is left to do?

**Comment by OH296** [comment]
there are two new types of unit introduced to the game
- sergeants (role[100, 18])
- veteran sergeants ( role[100, 19])
- both of which are automatically allocated in the squad whenever the existing one dies and selected from the marine with the highest exp

**Comment by GalacticChimp** [comment]
the sergeants are already done and merged or still in development?

**Comment by OH296** [comment]
TODO

- to do is to allow player customisation of squads and squad loadouts, e.g augment the optional and required equipment and the number and types of roles required in squads
- allow player to design from scratch their own squads without manually writing json files
- create a company view screen where the unit can view just the squads and not have to look at every individual marine
- squad stats? maybe although not sure what this would consist of

**Comment by OH296** [comment]
TODO
- assignment of squads to certain tasks e.g maybe guard or peacekeeping duty on a given planet (this needs some thought)

**Comment by GalacticChimp** [comment]
ok, we'll need to discuss, whether we have enough to allow a new release, or wait a bit

**Comment by OH296** [comment]
> the sergeants are already done and merged or still in development?

already merged re standard sergeants, however veteran sergeants are not i essentially have one last pr i'd like to do that would mean squads go out pretty much finished in the next version but it's basically just a bundle of tweaks as opposed to an introduction of featuring

**Comment by OH296** [comment]
new unit type veteran sergeants ( role[100, 19]) (both of which are automatically allocated in the squad whenever the existing one dies and selected from the marine with the highest exp)

now completed and merged
